#define REPLY_ACKNOWLEDGED          0x00
#define REPLY_NEED_TO_CLEAR         0x02
#define REPLY_NOT_ACKNOWLEDGED      0x01

#define	DEBUG	0
#define GET_TELEMETERIA 			1
#define SET_ACTIVE_BPS 				2
#define ENABLE_COMPENSATION_CHARGE 	3
#define ENABLE_CAPACITY_CONTROL 	4
#define DISABLE_BPS					5
#define CHECK_CONNECTION			6
#define DISABLE_SPECIAL_FUNCTIONS	7
#define UNLOCK_BPSS					8
#define ENABLE_PARRALEL_OPERATION	9
#define DISABLE_PARRALEL_OPERATION	10
#define RESET_ALL_ALARMS			11
#define GET_EVENTS_QUANTITY			12
#define GET_EVENT					13
#define GET_SETTINGS_TABLE			30
#define GET_SETTINGS_PARAMETER		31
#define SET_SETTINGS_PARAMETER		32
#define GET_DEVICE_INFO				33
#define GET_LOCATION_INFO			34
#define SET_EXTERNAL_IO				37
#define SET_LOAD_CTRL_VAR           38
#define SET_BATTERY_CTRL_VAR        39
#define GET_SYS_PARAMS_LIST			40
#define SET_SPARAM_INT				1
#define SET_SPARAM_INCREMENT		2
#define SET_SPARAM_DECREMENT		3
#define SEND_COMMAND_1_BYTE			21
#define SEND_COMMAND_2_BYTES		22
#define SEND_COMMAND_3_BYTES		23
#define SEND_COMMAND_4_BYTES		24
#define COMMAND_OK					77
#define COMMAND_INVALID				33
#define COMMAND_FAILED				66
#define COMMAND_TIMEOUT				55

#define FIRST_DATA_BYTE				4

GLOBAL extern struct PS_def PS;