
/* VALUES for ProConf */
#define PRO_NET         1            /* Network support */
#define PRO_V25         2            /* V.25 Processor */
#define PRO_S4M         4            /* SCC 4 Mhz */
#define PRO_TRB         8            /* TR Bridge function */
#define PRO_ADE         16           /* Ethernet autodetect */
#define PRO_SCA         32           /* scc auto detect */
#define PRO_RXTX        64           /* support rx/tx leds in dinrail */

/* Values for Conf */
#define PC_MINI         0x40         /* is CoBox mini - no SCC */
#define PC_LCXX         0x20         /* 24LCxx config memory */
#define PC_RTSL         0x10         /* RTS Latch (DinRail)    */
